spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bit_factory?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    baseline-on-migrate: true
