apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
  namespace: dev
spec:
  selector:
    app: bitfactory
  clusterIP: 10.97.97.97 # service的ip地址，如果不写，默认会生成一个
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080  # Service端口
      nodePort: 32082 # 指定绑定的node的端口(默认的取值范围是：30000-32767), 如果不指定，会默认分配