apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitfactory-deployment
  namespace: dev
spec:
  replicas: 2 #创建pod的个数
  selector:
    matchLabels:
      app: bitfactory #满足标签为这个的时候相关的pod才能被调度
  template:
    metadata:
      labels:
        app: bitfactory
    spec:
      containers:
        - name: bitfactory
          image: 127.0.0.1:5000/bitfactory
          ports:
            - containerPort: 8080